---
- name: Example Playbook
  hosts: 192.168.10.7
  become: true
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
      notify:
        - Restart Apache

    - name: Deploy Apache Docker Container
      docker_container:
         name: apache_container
         image: httpd
         state: started
         ports: 
           - "80:80"
        
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
